"""increase_neighborhood_and_frosting_type_limits

Revision ID: ad633f9e3077
Revises: 
Create Date: 2025-12-08 02:47:53.407841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad633f9e3077'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'neighborhood',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('listings', 'has_gumdrop_garden',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('listings', 'frosting_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('listings', 'listing_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('listings', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('listings', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('listings', 'listing_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('listings', 'frosting_type',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('listings', 'has_gumdrop_garden',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('listings', 'neighborhood',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
