"""increase_neighborhood_and_frosting_type_limits

Revision ID: ad633f9e3077
Revises:
Create Date: 2025-12-08 02:47:53.407841

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad633f9e3077"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # All operations wrapped in IF EXISTS to handle fresh databases
    # where tables are created by create_all() AFTER alembic runs
    op.execute("""
        DO $$
        BEGIN
            -- Only alter columns if listings table exists
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'listings') THEN
                -- Increase column sizes
                ALTER TABLE listings ALTER COLUMN neighborhood TYPE VARCHAR(200);
                ALTER TABLE listings ALTER COLUMN frosting_type TYPE VARCHAR(500);

                -- Update NULL values to defaults before adding NOT NULL constraints
                UPDATE listings SET has_gumdrop_garden = 0 WHERE has_gumdrop_garden IS NULL;
                UPDATE listings SET listing_type = 'cottage' WHERE listing_type IS NULL;
                UPDATE listings SET status = 'available' WHERE status IS NULL;

                -- Add NOT NULL constraints
                ALTER TABLE listings ALTER COLUMN has_gumdrop_garden SET NOT NULL;
                ALTER TABLE listings ALTER COLUMN listing_type SET NOT NULL;
                ALTER TABLE listings ALTER COLUMN status SET NOT NULL;
            END IF;

            -- Only alter users table if it exists
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'users') THEN
                UPDATE users SET is_active = 1 WHERE is_active IS NULL;
                ALTER TABLE users ALTER COLUMN is_active SET NOT NULL;
            END IF;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_active", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("listings", "status", existing_type=sa.VARCHAR(length=50), nullable=True)
    op.alter_column("listings", "listing_type", existing_type=sa.VARCHAR(length=50), nullable=True)
    op.alter_column(
        "listings",
        "frosting_type",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column("listings", "has_gumdrop_garden", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "listings",
        "neighborhood",
        existing_type=sa.String(length=200),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
